### PR TITLE
Add at-test macros to actually do the testing

### PR DESCRIPTION
**Pull request by giordano**
Note: tests are [failing on macOS, but passing on GNU/Linux](https://travis-ci.org/giordano/SoftPosit.jl/builds/527042987) and [FreeBSD](https://github.com/giordano/SoftPosit.jl/runs/116169947).  Not sure it's related, but I'll try to create a new build of the binaries, the Makefile included in SoftPosit is really really bad. (**Update**: rebuilding the binaries [didn't fix the failure](https://travis-ci.org/giordano/SoftPosit.jl/builds/527052290) on macOS.  You have a macOS, right?  Did tests pass for you with your manually built binaries?  I tried running the tests locally on my MacBook included here with both the binaries from BinaryBuilder and the library built manually and they fail in both cases with the same error reported by Travis).

PS: you should really enable Travis, AppVeyor, and Cirrus on this repository :wink:

### CODE REVIEW

**Comment by giordano** [comment]
For the record, tests are failing on Windows at the same point as on macOS: https://ci.appveyor.com/project/giordano/softposit-jl/builds/24255228
```
 Expression: Posit32(x) == Posit32(Posit16(Posit8_2(x)))
   Evaluated: Posit32(0x42000000) == Posit32(0x00000000)
```

**Comment by milankl** [comment]
Great job on the tests. Activated travis and appveyor, how do I do this with cirrus?

**Comment by giordano** [comment]
https://github.com/marketplace/cirrus-ci just select the free plan.  This is for FreeBSD (I think it's good to test as many platform as possible, including less common one, especially for packages depending on binaries.  I always use Cirrus for my packages depending on binaries)

**Comment by milankl** [comment]
> ```
>   Expression: Posit32(x) == Posit32(Posit16(Posit8_2(x)))
>    Evaluated: Posit32(0x42000000) == Posit32(0x00000000)
> ```
Also get that error on my mac. But it's both. Posit16(::Posit8_2) somehow rounds to 1 and Posit32(::Posit16) turns a 1 into a 0. The C calls should be correct. I'll raise that issue on Cerlane's repo.

**Comment by milankl** [comment]
Cerlane claims this bug was corrected. Can you test that? (Or how do I do that? =)

**Comment by giordano** [comment]
Usually we use tagged versions to create a new build.  I opened a [merge request](https://gitlab.com/cerlane/SoftPosit/merge_requests/2) to fix the basic issues with the `Makefile`, it'd be nice to have also that fix a new tagged version.

> Or how do I do that?

You can test on your machine by building your local clone of the C library and copy the resulting object to where `SoftPosit.SoftPositPath` points to.

**Comment by milankl** [comment]
Yep, I saw that PR on gitlab.
> You can test on your machine by building ...
That's what I did before you included the binary builder. What I meant is, whether we can run appveyor with the updated SoftPosit C repo?

**Comment by giordano** [comment]
> That's what I did before you included the binary builder.

You can still do that :wink:  Does it work for you?

> whether we can run appveyor with the updated SoftPosit C repo?

Uhm, I tried on my fork but I still get the same failures as before:

* Travis: https://travis-ci.org/giordano/SoftPosit.jl/builds/527785743
* AppVeyor: https://ci.appveyor.com/project/giordano/softposit-jl

**Comment by giordano** [comment]
Good news.  I commented in my fork the two failing tests: all other tests are passing ([AppVeyor](https://ci.appveyor.com/project/giordano/softposit-jl/builds/24295816), [Travis](https://travis-ci.com/giordano/SoftPosit.jl/builds/110582265))!

**Pull request merged**
