### PR TITLE
v0.3 with Julia 1.3 testing

### PR DESCRIPTION
**Pull request by milankl**

### CODE REVIEW

**Comment by milankl** [comment]
@JuliaRegistrator register

**Comment by giordano** [comment]
You'll need upper bounds in the "compat" section of `Project.toml` in order for the pull request to be automerged

**Comment by milankl** [comment]
You mean change
```julia
[compat]
BinaryProvider = "≥ 0.5.0"
julia = "≥ 1.0.0"
```
to
```julia
[compat]
BinaryProvider = "^0.5"
julia = "^1"
```

**Comment by giordano** [comment]
Yes, also without the carets, no leading sign is equivalent to the caret

**Pull request merged**
