### PR TITLE
Type stability of intermediates in conversions

### LINKED ISSUE #80: Float32 to Posit32 conversion yields unexpected results
While examining some conversions for a study, I stumbled that the conversion from Float32 to Posit32 does not work correctly. A number of other conversions work as expected.

```
Posit32: Posit32(-0.007027800427749753) Float32: -818.2957
Posit32: Posit32(-0.007557398173958063) Float32: -957.1266
Posit32: Posit32(0.005691442871466279) Float32: 489.9888
Posit32: Posit32(-0.007275644224137068) Float32: -883.2665
Posit32: Posit32(-0.006808562204241753) Float32: -760.8237
```
Other as expected. F64 to P32, P16, P8 and F32 to P16, P8
```
Posit32: Posit32(135.39814949035645) Float64: 135.39814949035645
Posit32: Posit32(245.05364990234375) Float64: 245.05364894866943
Posit32: Posit32(505.60044860839844) Float64: 505.6004524230957
Posit32: Posit32(-181.41913414001465) Float64: -181.41913414001465
Posit32: Posit32(-391.0908660888672) Float64: -391.09086990356445

Posit16: Posit16(-362.0) Float64: -362.2323274612427
Posit16: Posit16(-932.0) Float64: -931.7772388458252
Posit16: Posit16(-325.5) Float64: -325.4415988922119
Posit16: Posit16(837.0) Float64: 836.5764617919922
Posit16: Posit16(551.0) Float64: 551.0175228118896

Posit8: Posit8(-1024.0) Float64: -936.1075162887573
Posit8: Posit8(768.0) Float64: 755.1323175430298
Posit8: Posit8(-384.0) Float64: -422.3893880844116
Posit8: Posit8(-512.0) Float64: -526.3946056365967
Posit8: Posit8(512.0) Float64: 481.2452793121338

Posit16: Posit16(-237.625) Float32: -237.68079
Posit16: Posit16(-201.5) Float32: -201.4804
Posit16: Posit16(-299.5) Float32: -299.67523
Posit16: Posit16(-141.625) Float32: -141.65472
Posit16: Posit16(243.875) Float32: 243.85918

Posit8: Posit8(-384.0) Float32: -446.5549
Posit8: Posit8(768.0) Float32: 782.21906
Posit8: Posit8(-768.0) Float32: -877.843
Posit8: Posit8(-768.0) Float32: -697.1028
Posit8: Posit8(-384.0) Float32: -346.29642
```

How to reproduce:
Simplest syntax would be `Posit32(42.0f0)` or `Posit32(Float32(1337))` already leading to the error.

EDIT:
Just found out this only happens for for Float32 where the absolute value is 16 or bigger. For <16 everything is good.

```
julia> Posit32(-15.5f0)
Posit32(-15.5)

julia> Posit32(-15.9f0)
Posit32(-15.899999618530273)

julia> Posit32(-15.99f0)
Posit32(-15.989999771118164)

julia> Posit32(-16.0f0)
Posit32(-0.0625)

julia> Posit32(16.0f0)
Posit32(0.0625)
```

EDIT2:
The exponent seems to be interpreted as negative. The regime is starting with a 0. This could be something around the subtraction of the bias in the code I guess.
```
julia> (Posit32(16e0))
Posit32(16.0)

julia> (Posit32(16f0))
Posit32(0.0625)

julia> bitstring(Posit32(16e0))
"01100000000000000000000000000000"

julia> bitstring(Posit32(16f0))
"00100000000000000000000000000000"

julia> bitstring(Posit32(Float64(16f0)))
"01100000000000000000000000000000"
```

### PR DESCRIPTION
**Pull request by milankl**
fixes #80

### CODE REVIEW

**Comment by giordano** [comment]
Maybe add tests? 🙂

**Comment by milankl** [comment]
@Tobboss I've added one `signed` and one `unsigned` operation to the float -> posit conversion which removes some type instabilities we had. The extracted exponent bits were `UInt32` for Float32 and `Int64` for Float64

```julia
julia> Posit32(64f0)          # = (2^4)^k * 2^e, k = 1, e = 2 
[ Info: (UInt32, 0x00000002)  # typeof(e), e
Posit32(0.125)

julia> Posit32(64e0)
[ Info: (Int64, 6, false, 1)
[ Info: (Int64, 2)
Posit32(64.0)
```

**Comment by milankl** [comment]
> Maybe add tests? 🙂

Ja ha, bit embarrassing that this wasn't caught before ... 🙈

**Comment by milankl** [comment]
Okay so I've added some tests that check for power 2 conversions float->posit->float in the following ranges
(kmin, kmax) for the range `[2^k for k in kmin:kmax]` and `(2^kmin, 2^kmax)` after that 

```julia
[ Info: (Float64, Posit32, (-108, 108), (3.0814879110195774e-33, 3.2451855365842673e32))
[ Info: (Float32, Posit32, (-108, 108), (3.0814879110195774e-33, 3.2451855365842673e32))
[ Info: (Float64, Posit16, (-44, 44), (5.684341886080802e-14, 1.7592186044416e13))
[ Info: (Float32, Posit16, (-44, 44), (5.684341886080802e-14, 1.7592186044416e13))
[ Info: (Float64, Posit16_1, (-22, 22), (2.384185791015625e-7, 4.194304e6))
[ Info: (Float32, Posit16_1, (-22, 22), (2.384185791015625e-7, 4.194304e6))
[ Info: (Float64, Posit8, (-12, 12), (0.000244140625, 4096.0))
[ Info: (Float32, Posit8, (-12, 12), (0.000244140625, 4096.0))
```

but `Float16` is still fishy, e.g.

```julia
julia> Posit32(Float16(1))
Posit32(5.421010862427522e-20)

julia> Posit16(Float16(1))
Posit16(1.0)

julia> Posit8(Float16(1))
Posit8(1.0)
```

**Comment by milankl** [comment]
```julia
julia> bitstring(Posit32(Float16(1)))
"00000000000000000100000000000000"

julia> bitstring(Posit16(Float16(1)))
"0100000000000000"
```
something is not pushed in the right position

**Comment by milankl** [comment]
Okay it's about the `bitround` function that in case of "upcasting" (so not actually rounding) should just append 0s to the right, but that's currently not happening

```julia
julia> SoftPosit.bitround(UInt8, 0x1234)   # downcasting/rounding, correct
0x12

julia> SoftPosit.bitround(UInt16, 0x1234)   # uint16->uint16, identity, correct
0x1234

julia> SoftPosit.bitround(UInt32, 0x1234)    # uint16->32 upcasting, not correct
0x00000000
```

the latter should return `0x12340000` as for both floats and posits adding zeros to the right doesn't change the value

**Comment by milankl** [comment]
@tobboss with the last commit hopefully all conversions are corrected now. Would you mind checking your initial tests again and feed back here? I say "hopefully" because it's quite tricky to test all conversions between all possible posits and floats. You see that the tests I've formulated usually pick one aspect / special case of the conversion, some ranges are tested via lookup tables, some via back and forth conversion, some conversions are exact, some have to be rounded (to nearest, tie to even). 

I had some headaches with the float16 -> posit conversion as float16 subnormals require branching as their definition changes, such that the float16 subnormal mantissa impacts the posit regime and exponent bits. Kahan definitely owes me probably some weeks of my life because he thought that subnormals were a good idea. As I didn't want to go into the branching, I just defined float16->float32->posit, i.e. via conversion to float32 first. This is okay as float16 -> float32 is exact for all float16s, and conveniently converts all float16 subnormals to float32 normals. Float16 normals -> posit aren't a problem but well...

**Comment by milankl** [comment]
if you think that #80 is resolved then I'll merge and tag a new patch release

**Comment by Tobboss** [comment]
> @Tobboss with the last commit hopefully all conversions are corrected now. Would you mind checking your initial tests again and feed back here?

Hey Milan, thanks for the quick fix. I updated to the new branch and ran my test bench again. It looks very promising but my test is far from exhaustive. The elephant in the room is definately fixed.

I did a quick test and compared if random Float32 values converted to posit are still alike for the whole range of Float32. It was not so easy to find a suitable comparison, because I just got started with Julia and Posit, so I ended up comparing the higher significants and the exponents. It looks fine. The deviations that reside are normal near the min and max boundaries of the float.

**Pull request merged**
